# PyIceberg configuration for REST catalog
catalog:
  default:
    type: rest
    uri: ${NESSIE_URI}
    warehouse: ${ICEBERG_WAREHOUSE}
    s3.endpoint: ${MINIO_ENDPOINT}
    s3.access-key-id: ${MINIO_ACCESS_KEY}
    s3.secret-access-key: ${MINIO_SECRET_KEY}
    s3.region: ${MINIO_REGION}
    s3.path-style-access: true
